import { Inter } from "next/font/google";
import "./globals.css";
import Header from '@/components/wholeApp/header'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
          <div>
            <div style={{flex: '1'}}>
             <Header title={"Postagrid Grid Gallery"} msg={'Post and View Fractal Grids!'}/>
          </div>

          <div style={{flex: '9', padding: '2%'}}>
            {children}
          </div>
        </div>
        </body>
    </html>
  );
}
